i990 - Changed FontAwesome iconpicker location and added URL to view FA icons
uiowa/uiowa pull request #1083
Opened 2020-02-19 17:30 UTC by dnkemper

Changed FontAwesome icon picker location and added link to view all icons

 * When you filter icons, it stays in the same place - it's the only location that works (unless we want to display it inline where it's always visible)

2020-02-20 14:57 UTC, richardbporter requested changes
This results in horizontal scroll on mobile and the icon picker is off-canvas. I would recommend moving it to bottom and altering that field to disable browser autocomplete so it doesn't cover that.

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

2020-02-20 15:04 UTC, dnkemper commented
@richardbporter so should I change the issue gist? 'Fontawesome iconpicker floats away from the field it is attached to' because it would float away when using autocomplete... Then just say 'disable autocomplete and add link to font awesome icons'

2020-02-20 15:46 UTC, richardbporter commented
Yea that sounds good.

2020-02-21 20:02 UTC, joewhitsitt approved these changes

2020-02-21 21:16 UTC, merged