Improve runserver docs and hook.
uiowa/uiowa pull request #162
Opened 2019-05-08 19:47 UTC by richardbporter

Can someone give this a try? I can help.

2019-05-08 20:43 UTC, joewhitsitt commented on README.md
>      ```
Need to run `blt  blt:init:settings` to generate a local.setttings.php file for each site.

2019-05-08 20:44 UTC, joewhitsitt commented on README.md
> +    ```
it wasn't clear if I should leave namespace, driver, prefix defaults.

2019-05-08 20:46 UTC, joewhitsitt commented on README.md
> +    ```
I assume this is missing: `blt drupal:sync:all-sites` after the databases have been created

2019-05-08 20:48 UTC, joewhitsitt requested changes
If the Lando docs still work, I suggest leaving them in there and updating them one more time with the hiccups that we covered in last week's working session. we can flag lando as unsupported, but i may still use it as it works for me.

2019-05-08 20:58 UTC, joewhitsitt commented on README.md
>     ```
`brew link php@7.2` and follow steps about putting it first in your PATH

2019-05-08 21:35 UTC, joewhitsitt commented on README.md
> +9. Start the built-in PHP server.
Assumes drush is installed globally and Acquia Dev Desktop is not doing shady things in your bash_profile/bashrc

2019-05-09 13:31 UTC, richardbporter commented
Raw README: https://github.com/uiowa/uiowa/blob/b8d9bc8245c8002a3c07cc7b6f6504c4ee2168b5/README.md

2019-05-09 14:58 UTC, joewhitsitt approved these changes

2019-05-09 18:02 UTC, joewhitsitt commented
just tested with the latest commits. works as expected. made sure to lando destroy, lando stop, lando power off, quit docker, delete existing databases, and performed a git clean -ffdx before starting.

i already had php@7.2 and drush launcher setup with acquia dev desktop PATH stuff commented out.

2019-05-09 18:28 UTC, merged