Parent title field
uiowa/uiowa pull request #2152
Opened 2020-09-10 20:53 UTC by cory-skeers

Resolves #2048

2020-09-14 14:07 UTC, joewhitsitt commented
There was talk about the text area block as well, but I will let @pyrello make that pitch. ;)

2020-09-16 19:04 UTC, joewhitsitt commented
**Comment Status: In Progress**

First off, IMO the main field here should be the title which is optional. If filled/not empty #states should show the other fields with reasonable defaults (e.g. h2). This keeps the form simple if not filled out.

> For future options, do we need a minimal HTML field or similar, or can we use a plain, long field with tags like <hl> (or whatever is in place) that would be replaced with complete markup?

I think the short term is to allow certain html elements and classes without a ckeditor format/toolbar. Help text can supplement if we want to expose the possibilities to more than power users. If we need to make it more user friendly, I think it is a separate format from minimal.

> Any use case where you would want to set both title and children sizes separately

I can't think of a reason to do this, especially since most of these children headings don't actually change the visual size.

> Display title (boolean)
> How should this interact with children? Have a hidden title heading over visible children headings, or does this essentially mean don't use the title field?

The optional title paired with the heading size is what should control the children. The visually hidden title should still have a heading size and set the children appropriately.

>Styles?

Not sure what options currently exist beyond selecting the font. Unless there is a list we are going to start with, I think this could be something added later but "studded out" in preparation for.

> How does the hide title boolean (above) need to function?

With v2, we controlled this with an if statement in each template.

2020-09-17 14:07 UTC, pyrello commented
FYI, I am reviewing this information. I'll follow up with another comment with any feedback.

2020-09-30 15:07 UTC, joewhitsitt commented on docroot/sites/default/default.services.yml
> +parameters:
we don't want docroot/sites/default/default.services.yml and docroot/sites/default/services.yml

2020-09-30 15:28 UTC, joewhitsitt commented
Started looking at this, I haven't tested all the blocks, but I am noticing that:

I am not presented an option to set children headings if no parent title value is given.

Parent Title value with Visually hide is not rendering to the DOM which is the ideal to keep the heading order and to provide screen reader navigation.

I can try to help with this later.

2020-10-01 13:26 UTC, cory-skeers commented
Looks like an update somewhere has broken rendering the block headline on collections (haven't checked sliders, but they are likely to have also broken).

# Current to do:
- [ ] Fix bug that is preventing headline from rendering on collections (and possibly sliders)
- [ ] Present an option to set child heading size if title field is not filled

2020-10-06 13:45 UTC, joewhitsitt commented
pulling down for testing

2020-10-06 15:33 UTC, joewhitsitt commented
- Not loving the help text related to children items.
  - _"The heading size for the block title. Children headings will be set one heading level lower."_
  - _"The heading size for all children headings."_
  - Text area is not a "collection" so children help text doesn't apply and confuses me thinking that it will adjust headings within WYSIWYG (text area). form_alter change help text?
  - Image Gallery does not have children headings. form_alter change help text?
- headline has no targetable classes to style against. is there a uids default heading class that should apply here? `headline`
- not working on slider/collections.
- collection descriptive list didn't adjust child items. not sure it should, but again, the help text should reflect that.
  -  _"The heading size for the block title. Accordion item headings will be set one heading level lower. Does not apply to descriptive list."_
- don't think we should allow h6 for parent as there is no h7 to apply to children.

2020-10-06 15:49 UTC, cory-skeers commented
Good points re: the help text areas. Think I'd started not really seeing them anymore, and they need updating.

For the sliders/collections not working, is it not setting the child heading levels, not displaying the headline, etc., or not working entirely?

2020-10-06 15:55 UTC, joewhitsitt commented
I think i set a h5 for slider parent title, and saw h3s for the single child i had. Collection accordions seemed to be similar. i can double check here in a bit. maybe it was limited to layout preview?

2020-10-06 16:23 UTC, cory-skeers commented
Made some updates to the help text, and its implementation for specific block use cases.

Removed the option for `h6` for headlines in cases where children are expected to be present, leaving it for the child heading option and blocks which don't have children (text area, image gallery).

2020-10-06 18:01 UTC, cory-skeers commented
Ah..yes. It looks like the original lb editor preview does not accurately set the child heading sizes, but it is set correctly after saving (for both viewing the page, and later viewings in the editor preview).

Not a breaking issue, but would be nice to get working in the original preview in case it may impact later styling options, and just for full accuracy in previews. Will look into it and/or create a follow-up issue for it.

2020-10-07 13:28 UTC, cory-skeers commented
# To do
* Refactor theming templates to utilize uids `heading.html.twig`
* Include heading style options
* Track down editor preview heading difference bug

2020-10-07 14:49 UTC, bspeare commented
@cory-skeers are you able post screenshots and describe the style issues that you mentioned in standup?

2020-10-07 15:52 UTC, cory-skeers commented
@bspeare Adding the headline style options directly to the blocks that are using the headline field keeps it consistent with other block types, but without other adjustments gets confusing as to what it controls.

In the example below, the headline style options are added for an Articles block, but it's unclear if it should be applying to the overall block headline, the individual article headlines, or both. Depending on what kinds of options should be available, we could move the element on the form to make it clear it only effects the block headline, use it to effect all headlines, or add the styles directly to the uiowa_block_headline field where it could be handled separately from the children headlines and their possible styling.

![image](https://user-images.githubusercontent.com/49074566/95354218-c561e100-0889-11eb-861b-86809705f7ce.png)

2020-10-07 18:36 UTC, bspeare commented
@cory-skeers it would be interesting to see the "Headline options" within the block headline form section.   I'd also want to maybe limit the "Headline options" available.     Is that style option available in this PR?  I just tested this on uiowa.local and I don't see it.

2020-10-07 18:43 UTC, bspeare commented
@cory-skeers At this point, for example, I don't think we want to change the headline style for each entry in the articles list since each component has a set grouping of styles.   I think the idea of changing the style of the block title is very appealing since most sites want to set a style for that heading or will do so by adding a separate block above if they really want to set a headline style.

2020-10-07 19:04 UTC, cory-skeers commented
@bspeare The style option isn't available yet in the PR (I'd been working with a half combo of this and the banner block refactor), but I'll start working on that next (including it with the field, so its more clear what its effecting) and let you know when it's available!

Do you have an idea of which styles we'd want to include, or which to limit?

2020-10-07 20:05 UTC, bspeare commented
@cory-skeers I'd probably want to start with just a few options like Zilla Slab or Zilla Slab with an underline:

<img width="714" alt="Screen Shot 2020-10-07 at 3 02 47 PM" src="https://user-images.githubusercontent.com/1036433/95381776-3e732f80-08ae-11eb-8301-ed6ad9f7f4b5.png">

2020-10-07 21:39 UTC, cory-skeers commented
Refactored the field render to use `headline.twig.html`, and provide some classes (and some flexibility in adding/updating classes later). Also took a stab at getting style options in place.

![image](https://user-images.githubusercontent.com/49074566/95389668-c6126b80-08b9-11eb-994c-dad903d3268b.png)

Not a fan of how it's implemented (as a separate 'style' field, rather than using layout_builder_styles), but the main drawbacks of this way would be the slight difference in form style (screenshots below) and not automatically getting headline options pulled in. The former could be addressed through css, and the latter isn't too bad if these headlines will only be using a controlled subset of the full set.

![image](https://user-images.githubusercontent.com/49074566/95389938-2f927a00-08ba-11eb-844d-2fbec45cfd33.png)
![image](https://user-images.githubusercontent.com/49074566/95389836-01ad3580-08ba-11eb-86ae-89a513f8a898.png)

2020-10-07 22:49 UTC, bspeare commented
@cory-skeers Thanks for posting the screenshots.   I think we might want to set fixed font sizes based on what layout column the block headline is within.  And s centered alignment option if we want editors to avoid creating a separate one column layout to create headings.  For instance, in one column layouts the heading would be sized larger. 

<img width="1942" alt="Screen Shot 2020-10-07 at 5 47 25 PM" src="https://user-images.githubusercontent.com/1036433/95395869-3a9ed780-08c5-11eb-9e41-f0cafcf8f7cb.png">

2020-10-08 18:04 UTC, cory-skeers commented
@bspeare Are there fixed font sizes in place for any other components, and/or existing classes/variables to use, or will setting this need to be a new addition?

I'm also wondering about the center alignment option--would this be a single centered headline set above the content in the separate columns? My initial thought is then to provide a "section headline" option as well, where the section could have a headline, and each column/block could have a headline. But that also feels like blowing up the headline options...

2020-10-08 21:12 UTC, bspeare commented
@cory-skeers I think we might want to have the alignment informed by https://github.com/uiowa/uiowa/issues/2309.  

For the font size, perhaps we could start by setting it to `2.2rem` initially?

<img width="1398" alt="Screen Shot 2020-10-08 at 4 11 37 PM" src="https://user-images.githubusercontent.com/1036433/95514125-1274ae80-0981-11eb-9f21-5f13fd22df3d.png">

2020-10-09 15:56 UTC, pyrello commented on config/default/field.field.block_content.uiowa_articles.field_uiowa_block_headline.yml
> +label: 'Block Headline'
I think this could just be called 'Headline'.

2020-10-09 15:57 UTC, pyrello commented on config/default/field.field.block_content.uiowa_articles.field_uiowa_block_headline.yml
> +label: 'Block Headline'
And in any other place this label is used also.

2020-10-09 16:00 UTC, pyrello commented on config/default/layout_builder_styles.style.headline_all_caps.yml
> +label: 'Headline all caps'
I'm going to adjust these labels in #2075. This will need to be adjusted after that is merged.

2020-10-09 21:38 UTC, bspeare commented
@cory-skeers are we able to target the heading field with a `block-title` class so that we can modify that size to `2.2rem`?  Would we add that here: https://github.com/uiowa/uiowa/pull/2152/files#diff-77fb9c8aa4d0580e6b5f78be4c85c98a? 

The other thing I noticed is that the heading option says "Bold Headline highlight" when it should be "Bold headline underline".

2020-10-11 14:47 UTC, pyrello commented
Does it need to be `block-title`? It might be good to name it something more generic in case this is used outside of blocks.

2020-10-12 13:04 UTC, cory-skeers commented
@pyrello It doesn't need to be named block specific. It might help to have a specific label or description in some places (collections, articles, etc.) to make its relationship to the children elements clear, but we can add that as needed--might be more clear on a per-block basis, anyway.

Any votes for replacement for `uiowa_block_headline` to namespace it outside of block? `uiowa_headline`, `uiowa_title`, or others.

2020-10-12 16:09 UTC, pyrello commented
I think the class should just be `headline`. I'm pretty sure that shouldn't conflict with anything internal and would be consistent with how we will eventually rename all the headline classes to `headline--bold--` style names.

2020-10-12 19:45 UTC, cory-skeers commented
Reworked machine names, field labels, etc., updated headline highlight to underline in label, and added a default `headline` class for scoping styling.

@bspeare Right now it sets headlines using the field to `2.2rem` unless it's in a one-col section, where it is set to `2.3rem`, to check that scoping works as intended.

2020-10-14 16:01 UTC, richardbporter commented
Is it possible to use this field programmatically? The aggregator block is provided by the uiowa_aggregator module in #2296 so I can't add the field through the UI.

2020-10-14 18:11 UTC, pyrello commented
I'm working on fixing the merge conflicts.

2020-10-14 18:33 UTC, richardbporter commented
If this is ready to go, I can work to add a custom render element after this merged as part of #2296.

2020-10-14 19:58 UTC, richardbporter commented
I guess I'm going to rebuild #2296 using the field API unless someone thinks otherwise. 😢

2020-10-14 20:42 UTC, cory-skeers commented
@richardbporter Sorry it took awhile to see this!

The field should be usable to be added programmatically with this--it gets defined as a complete, separate fieldtype (uiowa_headline).

From my standpoint, this is done other than review and testing (and possibly updating stylenames following the banner_block_refactor PR). Some things like a centered section option, or fine-tuning sizing based on column placement can continue to be added/adjusted after merging.

2020-10-15 15:49 UTC, richardbporter commented
My understanding is that its not possible (or easy) to use the field API in the forms API. I think we'd need to implement a custom form element using https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21Element%21FormElement.php/class/FormElement/8.9.x - like the address module is doing.

In the interest of time, I rebuilt the aggregator block using the field API. I was able the get this field working without any major issues in #2296. Nice job! 👍

2020-10-15 16:24 UTC, richardbporter commented
Did anyone test the update hook? Are there specific sites to test with the hook? Otherwise, I'd like to get this merged for #2296  if nobody has other changes.

2020-10-15 16:35 UTC, joewhitsitt commented
haven't tested since 9 days ago. not going to be able to do it before this PM.

2020-10-15 17:58 UTC, joewhitsitt commented
>Are there specific sites to test with the hook?

Same question.

2020-10-15 18:25 UTC, cory-skeers commented
The default content on fresh installs can be used to check that the Articles and Events headlines get set correctly, as well as slider (although possibly less noticeable, since it'd get set as an h2). People and Collections, I'm not sure of any examples in the wild.

2020-10-15 21:44 UTC, richardbporter requested changes, later dismissed
Just noticed that https://github.com/uiowa/uiowa/commit/2f8ab63464eec1aab47248ec234346838370b638 was somehow lost in I'm assuming a merge conflict resolution into this PR. We'll want to double check that and any other regressions.

2020-10-15 21:47 UTC, richardbporter commented
I got sitenow_update_8035 to run on the default site without issue. Didn't know exactly what to look for but heading size was set to what it was before. 👍

2020-10-15 21:58 UTC, cory-skeers commented
Shoot. Hopefully there aren't many regressions in here outside of that one.

@richardbporter If that worked, then we're good! All the update hook should do is set the appropriate heading level if one had been set prior to this new field. Just had a little extra roundabout to make sure the config gets pulled in with the right order to get it updated and avoid config errors.

2020-10-15 22:03 UTC, richardbporter commented
I can try to find the offending commit tomorrow and reimplement the changes.

________________________________
From: cory-skeers <notifications@github.com>
Sent: Thursday, October 15, 2020 4:58:20 PM
To: uiowa/uiowa <uiowa@noreply.github.com>
Cc: Porter, Richard B <richard-b-porter@uiowa.edu>; Mention <mention@noreply.github.com>
Subject: [External] Re: [uiowa/uiowa] Parent title field (#2152)


Shoot. Hopefully there aren't many regressions in here outside of that one.

@richardbporter<https://github.com/richardbporter> If that worked, then we're good! All the update hook should do is set the appropriate heading level if one had been set prior to this new field. Just had a little extra roundabout to make sure the config gets pulled in with the right order to get it updated and avoid config errors.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/uiowa/uiowa/pull/2152#issuecomment-709612020>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAIE3273XEEAWWCYRNUKI63SK5V7ZANCNFSM4RF3EPRA>.

2020-10-16 13:47 UTC, richardbporter commented
Looks like this was introduced with the banner block refactor https://github.com/uiowa/uiowa/commit/1fd282c7e025f8184b14493024b6b1f3c7230b5b#diff-22455fd1cfa159b58a0289784a91064192c27738f06b23e252be3a46271afb4c. I guess I'll create a fix off main.

2020-10-16 14:04 UTC, richardbporter commented
Cleared my review as I found the regression was unrelated to this PR.

2020-10-16 17:01 UTC, richardbporter commented
On fresh install, i.e. `blt drupal:install`, I'm getting the following error when editing the layout of the front page:
```
Twig\Error\LoaderError: Template "@uids_base/uids/heading.html.twig" is not defined in "themes/custom/uids_base/templates/field/field--field-uiowa-headline.html.twig" at line 47.
```

I compiled frontend assets... Anyone know if a template changed again? Otherwise I can dig into it.

2020-10-16 18:10 UTC, cory-skeers commented
@richardbporter Looks like a few template updates were needed. Think I got them all.

2020-10-16 18:39 UTC, richardbporter approved these changes

2020-10-16 18:48 UTC, merged