Add d8 site provision docs
uiowa/uiowa pull request #285
Opened 2019-06-21 14:45 UTC by ethanstjohn

2019-06-21 15:03 UTC, richardbporter requested changes

2019-06-21 15:03 UTC, richardbporter commented on README.md
> +2. Respond 'no' when prompted for database credentials. If it fails, run it again with --no-interaction.
It should always be run with this option.

2019-06-21 15:03 UTC, richardbporter commented on README.md
> +3. Review the code changes and commit to a feature branch.
This is done automatically.

2019-06-21 15:03 UTC, richardbporter commented on README.md
> +4. Run the Drush snippet given to install the site locally.
This is done automatically.

2019-06-21 15:03 UTC, richardbporter commented on README.md
> +6. Create the database and domains in the Acquia Cloud UI.
The database is created automatically.

2019-06-21 15:03 UTC, richardbporter commented on README.md
> +7. Once merged and deployed, the database can be synced in the following order. Dev -> Stage/Test -> Prod. Make sure to clear the site's cache.
We need to specify that Drush should not be used to sync the database initially because it will bootstrap the wrong site.

2019-06-21 15:03 UTC, richardbporter commented on README.md
> +*Example:* "drush @uri.dev cr" --> "drush sql:sync @uri.local @uri.dev". If the sql:sync fails try, "drush -l uri.uiowa.edu rsync @self:%files @uri.dev:%files".
The Cloud UI should be used to sync the database initially.

2019-06-21 20:49 UTC, ethanstjohn reviewed
I updated the docs.

2019-06-28 14:21 UTC, richardbporter commented
My feedback wasn't great, sorry. I think it would be best to avoid duplicating docs that the RMI command is printing out. I simplified this.

2019-06-28 14:27 UTC, richardbporter approved these changes
I actually don't think we need any docs on this besides "run the command and follow the directions it prints" otherwise we are duplicating docs.

2019-06-28 14:27 UTC, merged

2019-06-28 14:35 UTC, ethanstjohn commented
No problem! Thank you for helping me review this.