Acc style updates
uiowa/uiowa pull request #3053
Opened 2021-02-11 19:33 UTC by GaryRidgway

# How to test

2021-02-15 13:41 UTC, richardbporter requested changes

2021-02-15 13:41 UTC, richardbporter commented on docroot/sites/blt.development.services.yml
> +    debug: false
I think this should stay set to `true` as it is only loaded in the local development environment.

2021-04-15 21:07 UTC, richardbporter commented
Just posting here what we mentioned earlier. @GaryRidgway Do you know if this PR is still needed?

2021-04-19 15:50 UTC, GaryRidgway commented
@richardbporter I think this PR has basically just become outdated. For some reason it was gutted at some point and things have changed so much that I think there is a need for us to take another serious pass using this PR as a reference when we do.

2021-04-22 14:00 UTC, closed without merging