Featured content block type
uiowa/uiowa pull request #3544
Opened 2021-05-19 15:34 UTC by pyrello

# How to test

2021-05-19 21:14 UTC, joewhitsitt commented
Docs - https://github.com/uiowa/uiowa/issues/3546

2021-05-19 21:22 UTC, richardbporter requested changes
Seems like the heading child size field is visible when initially adding the block. Probably a states issue with an empty value in the headline text field.

2021-05-19 21:31 UTC, richardbporter reviewed
Tested child heading size change.

2021-05-20 14:08 UTC, richardbporter approved these changes

2021-05-20 16:51 UTC, merged