Adjusted replicate node confirmation form text, fixes #4346
uiowa/uiowa pull request #4347
Opened 2021-10-22 13:59 UTC by quamsta

Trying to make the replicate page confirmation dialog a bit more friendly and more tailored to our current use case for the module: replicating pages. 

Changes:

- The title "Are you sure you want to replicate _node_ entity id [id]?" now reads "_Replicate Page_ [Page Name]," which matches the "_Edit Page_ [Page Name]" action title.
- The field label "New label (English)" now says "Replicated page's title"
- The description "This text will be used as the label of the new entity being created, in English." now says "This text will be used as the title of the newly replicated page."
- Removed the potentially confusing "This action cannot be undone." message 

Before:
<img width="925" alt="Screen Shot 2021-10-22 at 8 54 48 AM" src="https://user-images.githubusercontent.com/472923/138466103-c7812f46-bbe3-4584-85b6-71e885028530.png">

After:
<img width="984" alt="Screen Shot 2021-10-22 at 8 51 28 AM" src="https://user-images.githubusercontent.com/472923/138466120-435a477a-3e57-4337-a801-940c6ff88689.png">

# How to test

Replicate a page to see these adjustments (after clearing the cache).

2021-10-22 14:33 UTC, joewhitsitt commented
So, replicate is also enabled for articles. It is also capable of being extended to other content types by developers. Can we look into ways to generalize when this fires and then gets the bundle name to use in the language?

Also, I think "This action cannot be undone" should be left in but can be modified to be more clear. This statement is common around Drupal for things (deleting content, etc.)

2021-10-22 14:50 UTC, pyrello commented on docroot/modules/custom/uiowa_core/uiowa_core.module
> +        $form['new_label_en']['#title'] = 'Replicated page\'s title';
You can use double quotes to avoid needing to escape the single quote here.

2021-10-22 14:50 UTC, pyrello commented on docroot/modules/custom/uiowa_core/uiowa_core.module
> +        $form['new_label_en']['#title'] = 'Replicated page\'s title';
FWIW, this is the only time I will suggest using double quotes :)

2021-10-22 14:53 UTC, pyrello commented on docroot/modules/custom/uiowa_core/uiowa_core.module
> +        $form['#title'] = t('<em>Replicate Page</em> @title', ['@title' => $node_title]);
Per @joewhitsitt's comment, get the entity bundle to generalize "Page" to be whatever bundle type is being replicated. Since technically, this could apply to non-node entities, it might be good to add a check if the entity type is node and then set this title based on the bundle.

2021-10-22 14:53 UTC, pyrello requested changes
See individual comments.

2021-10-22 14:54 UTC, quamsta commented
> So, replicate is also enabled for articles. It is also capable of being extended to other content types by developers. Can we look into ways to generalize when this fires and then gets the bundle name to use in the language?

Oh! Yes, I'll see if I can find a way to genericize it. Good call

> Also, I think "This action cannot be undone" should be left in but can be modified to be more clear. This statement is common around Drupal for things (deleting content, etc.)

Up for any ideas, but I feel "This action cannot be undone" is pretty unclear in this case. Makes sense for deleting items or other potentially destructive actions, but it might be a little harsh for something like copying an item.

2021-10-22 14:55 UTC, joewhitsitt commented on docroot/modules/custom/uiowa_core/uiowa_core.module
> +        $form['#title'] = t('<em>Replicate Page</em> @title', ['@title' => $node_title]);
would have to change how you get to the right form to alter though. currently `node_page_replicate_form` maybe there is another identifier that you can latch on to

2021-10-22 15:07 UTC, joewhitsitt commented
>Up for any ideas, but I feel "This action cannot be undone" is pretty unclear in this case. Makes sense for deleting items or other potentially destructive actions, but it might be a little harsh for something like copying an item.

Yeah, that is fair. It wasn't too long ago that this action was causing database corruption. Glad Cory found a fix and we are where it is today, but I am crossing my fingers each time that button is pushed. I guess the publisher doesn't need to know all that and "for your developer's sake, please use sparingly" doesn't quite roll off the tongue. I will back down on this change.

2021-10-22 15:35 UTC, quamsta commented
> > Up for any ideas, but I feel "This action cannot be undone" is pretty unclear in this case. Makes sense for deleting items or other potentially destructive actions, but it might be a little harsh for something like copying an item.
> 
> Yeah, that is fair. It wasn't too long ago that this action was causing database corruption. Glad Cory found a fix and we are where it is today, but I am crossing my fingers each time that button is pushed. I guess the publisher doesn't need to know all that and "for your developer's sake, please use sparingly" doesn't quite roll off the tongue. I will back down on this change.

Yeah, totally understand the reasoning behind wanting to keep a message like that with the difficulties the module presented, but from a user perspective the "cannot be undone language" may present the question of "should I not be doing this?" and I also had a user ask "Is it referring to the title field not being able to be changed after the fact?" since the message was showing up directly under the title field.

2021-10-22 15:36 UTC, quamsta commented
Also @joewhitsitt, I just committed a change that should allow for any allowed replicated content type to be referred to in this dialog (instead of just pages). I did a hacky "ucfirst()" to get the content type label to be uppercase in the title attribute, but if you know a better way to do that, please help haha.

2021-10-22 15:49 UTC, joewhitsitt commented
More processing but I think something like this would work and handle a world of multi-worded names in the future (e.g. Areas of Study):

```php
$bundle_label = \Drupal::entityTypeManager()
  ->getStorage('node_type')
  ->load($node->bundle())
  ->label();
```

>Since technically, this could apply to non-node entities, it might be good to add a check if the entity type is node and then set this title based on the bundle.

A lot of our code so far is only focused for "content" based on the replicate settings, so let's hold off of on future-proofing for all entities.

2021-10-22 16:00 UTC, quamsta commented on docroot/modules/custom/uiowa_core/uiowa_core.module
> +        $form['#title'] = t('<em>Replicate Page</em> @title', ['@title' => $node_title]);
Ended up using the `if ($route_name == 'entity.node.replicate') {` statement that's already being used instead of `node_page_replicate_form`

2021-10-22 19:31 UTC, quamsta commented
> More processing but I think something like this would work and handle a world of multi-worded names in the future (e.g. Areas of Study):
> 
> ```
> $bundle_label = \Drupal::entityTypeManager()
>   ->getStorage('node_type')
>   ->load($node->bundle())
>   ->label();
> ```
> 
>  > Since technically, this could apply to non-node entities, it might be good to add a check if the entity type is node and then set this title based on the bundle.
> 
> A lot of our code so far is only focused for "content" based on the replicate settings, so let's hold off of on future-proofing for all entities.

Okay, this is now using the bundle's label() instead of node_type. This does create a minor grammatical issue where the label is now capitalized when it maybe shouldn't be (e.g.,the  "Replicated Article's title" field label should probably be "Replicated article's title," since I've seen "article" and "page" used in lowercase before, but it's probably not a huge deal?

2021-10-22 20:50 UTC, joewhitsitt commented
pulling down to test

2021-10-22 21:33 UTC, joewhitsitt commented
I guess I misunderstood what you went with ucfirst() originally when providing you a way to get the human readable label.

Hope you don't mind, but I tweaked this a bit to get the best of both worlds. I still think the human readable label should be used but that it should be lower case. I think you protect yourself from apostrophe errors in the future "content" can be squeezed in. (e.g. senior thesis content's title).

<img width="588" alt="Screen Shot 2021-10-22 at 4 03 30 PM" src="https://user-images.githubusercontent.com/4663676/138523112-3e015d0f-c50f-4d78-a82a-adc1ffba2bee.png">

<img width="634" alt="Screen Shot 2021-10-22 at 4 31 24 PM" src="https://user-images.githubusercontent.com/4663676/138525261-7fa4e565-e388-4445-b9eb-ca2df8433344.png">

I am going to approve, but if you disagree with my change, we can revert and go a different way.

2021-10-22 21:33 UTC, joewhitsitt approved these changes

2021-10-22 21:37 UTC, quamsta commented
> I guess I misunderstood what you went with ucfirst() originally when providing you a way to get the human readable label.
> 
> Hope you don't mind, but I tweaked this a bit to get the best of both worlds. I still think the human readable label should be used but that it should be lower case. I think you protect yourself from apostrophe errors in the future "content" can be squeezed in. (e.g. senior thesis content's title).
> 
> <img alt="Screen Shot 2021-10-22 at 4 03 30 PM" width="588" src="https://user-images.githubusercontent.com/4663676/138523112-3e015d0f-c50f-4d78-a82a-adc1ffba2bee.png">
> 
> <img alt="Screen Shot 2021-10-22 at 4 31 24 PM" width="634" src="https://user-images.githubusercontent.com/4663676/138525261-7fa4e565-e388-4445-b9eb-ca2df8433344.png">
> 
> I am going to approve, but if you disagree with my change, we can revert and go a different way.

This is great! Thanks a ton Joe! Have a good weekend.

2021-10-25 13:29 UTC, pyrello approved these changes
Approving based on @joewhitsitt's approval.

2021-10-25 13:32 UTC, merged