Enable remote video on card block
uiowa/uiowa pull request #4375
Opened 2021-10-29 17:25 UTC by makurj

Resolves #2724 

# How to test

As a content editor, I can add a remote video to a card. Do the "image format" and "image size" fields disappear on video addition?

## Expected behavior

### Video

If "Image position" is set to Stacked, the image size options should not be available.

<img width="648" alt="Screen Shot 2021-11-03 at 1 42 39 PM" src="https://user-images.githubusercontent.com/1036433/140173208-e5a20a9c-dc3d-4e84-aa47-7e2f1239acc9.png">

If "Image position" is set to Right or Left, the Large and Medium image size options should appear:

<img width="671" alt="Screen Shot 2021-11-03 at 1 42 48 PM" src="https://user-images.githubusercontent.com/1036433/140173212-0390d7ca-5afb-44ed-83f0-b36750071d44.png">

<img width="644" alt="Screen Shot 2021-11-03 at 1 42 56 PM" src="https://user-images.githubusercontent.com/1036433/140173220-10ea0463-a0de-4e5f-b863-0e2e28dfc79a.png">

### Image

If "image format" is set to Circle and "Image position" is Stacked, then image size options should appear.  

<img width="658" alt="Screen Shot 2021-11-03 at 1 43 39 PM" src="https://user-images.githubusercontent.com/1036433/140173222-89815139-27ae-4d4f-85b8-573549c16e10.png">

If "Image position" is set to Right or Left, the "Image size" options should be available no matter what the "Image format" is set to. 

<img width="648" alt="Screen Shot 2021-11-03 at 1 43 49 PM" src="https://user-images.githubusercontent.com/1036433/140173223-8a38f3f0-5fc0-4456-a45c-a657bc20cd18.png">
<img width="642" alt="Screen Shot 2021-11-03 at 1 43 54 PM" src="https://user-images.githubusercontent.com/1036433/140173224-7723325d-b297-4a63-8154-d1ccf7100d2b.png">

2021-11-02 14:58 UTC, bspeare commented
I think we also might want to hide the `small` and `medium` image size options and set the default to `large`.   Here's what a video would look like if set to `small`:

<img width="465" alt="Screen Shot 2021-11-02 at 9 56 46 AM" src="https://user-images.githubusercontent.com/1036433/139872385-70928a1c-09a3-4bd1-902a-6d9f914e82c4.png">

<img width="669" alt="Screen Shot 2021-11-02 at 9 57 06 AM" src="https://user-images.githubusercontent.com/1036433/139872411-1c331d9a-c8ff-46f9-a5bf-9f17ca00807f.png">

2021-11-02 15:10 UTC, pyrello commented
@bspeare If it is showing that option while video is selected, then that is not the intended behavior. I would request changes to that effect.

2021-11-02 15:12 UTC, bspeare commented
@pyrello Thanks, I will look closely at this and make the request.

2021-11-02 15:22 UTC, bspeare requested changes
The "Image size" option is still appearing when I have set a remote video and as soon as I select "Right" or "Left" alignment the "Image size" select option appears. 

<img width="643" alt="Screen Shot 2021-11-02 at 10 21 41 AM" src="https://user-images.githubusercontent.com/1036433/139876761-f6c51a57-d537-433e-9043-f544d9f03f65.png">

2021-11-02 15:53 UTC, bspeare commented
Looks like `card-block-form.js` is not loading on the page.

2021-11-03 13:51 UTC, makurj commented
Intended behavior for image: if image position is stacked, and circle is image format, image size shows up. Image size doesn’t show up for square and widescreen. If left is selected for position. With left for image position, no matter the image format, image size is always visible. Same with right image position.

Intended behavior for remote video: Image size and image format should not be visible irrespective of image position options.

2021-11-03 14:10 UTC, pyrello commented on docroot/modules/custom/layout_builder_custom/js/card-block-form.js
>          const $image_size_field = $form_wrapper.find('.form-item-layout-builder-style-card-image-size').find('select, label');
I'm not sure about this approach. If I'm not mistaken, how this works is that you are hiding the `<label>` and `<select>` element, while leaving the `<div>` wrapper that contains them visible. While this technically works, it feels a bit like a kludge.

2021-11-03 14:16 UTC, bspeare commented on docroot/modules/custom/layout_builder_custom/js/card-block-form.js
>          const $image_size_field = $form_wrapper.find('.form-item-layout-builder-style-card-image-size').find('select, label');
Good point!  We are still refining this a bit.

2021-11-03 18:11 UTC, bspeare commented on docroot/modules/custom/layout_builder_custom/js/card-block-form.js
>          const $image_size_field = $form_wrapper.find('.form-item-layout-builder-style-card-image-size').find('select, label');
@pyrello Line 15 has been changed.   Do you have an issue with line 14 too?

2021-11-03 18:53 UTC, bspeare commented
I've updated the testing instructions with screenshots explaining the Display options to test.

2021-11-03 19:59 UTC, dnkemper commented
I can review this as an outside perspective since I haven't been involved in any discussion or work if that's okay? 🤷🏼‍♀️

2021-11-03 20:10 UTC, makurj commented
Sure! @dnkemper
Thanks, @bspeare for updating the issue with amazing screenshots!

2021-11-03 20:27 UTC, dnkemper commented
- [x] If "Image position" is set to Right or Left, the "Image size" options should be available no matter what the "Image format" is set to.
- [x] If "image format" is set to Circle and "Image position" is Stacked, then image size options should appear.
- [x] If "Image position" is set to Right or Left, the Large and Medium image size options should appear:
- [x] If "Image position" is set to Stacked, the image size options should not be available.
^^all pass in the testing - LOVE the screenshots btw to make sure I'm on the right track. Question though.. is there a way to set a name then or not? If not, why does it allow you to search the videos by name if the name can't be set? Can only set tags. Not sure if this matters or not? Looks great though other than that

2021-11-03 20:43 UTC, makurj commented
Thanks @dnkemper. That is odd. We don't have the option to add a name when uploading a remote video but we can add tags, and searching by tags works great. The name works also, but only if you know the name of the video from the source.

2021-11-03 21:07 UTC, dnkemper commented
@makurj OH! Okay! If that's the desired functionality, then I'm good on approving unless @bspeare wants more changes?

2021-11-03 21:14 UTC, bspeare submitted a review, later dismissed

2021-11-04 15:57 UTC, bspeare requested changes
I am encountering an issue where the "Small" size remains if I update an existing card that was using the "Small" image size.   Try editing one of the left aligned small cards on https://sandbox.local.drupal.uiowa.edu/node/21/layout. 

<img width="1750" alt="Screen Shot 2021-11-04 at 10 54 55 AM" src="https://user-images.githubusercontent.com/1036433/140373964-540e2cdf-56ef-4b05-9055-040de6860888.png">

2021-11-04 16:16 UTC, bspeare approved these changes
That fixed the issue! Nice work @makurj !

2021-11-04 16:17 UTC, makurj commented
Thanks for all your help @bspeare!

2021-11-04 16:22 UTC, merged