Feature webform styling
uiowa/uiowa pull request #5130
Opened 2022-04-12 20:42 UTC by bewoldt

Resolves #4954 

# How to test

**For tippie form example**
1. Pull down tippie.students
`blt ds --site=students.tippie.uiowa.edu`
2. visit the page: https://tippiestudents.uiowa.ddev.site/undergraduates/get-involved/tippie-top-21/submit-tippie-top-21-nomination
3. Check to see if it matches the notes referenced in #4954.

**To test all available form fields**
1. Pull down sandbox prod
`blt ds --site=sandbox.uiowa.edu`
2. Test the page https://sandbox.uiowa.ddev.site/form

2022-04-13 13:38 UTC, joewhitsitt commented
Is this ready for review @bewoldt?

2022-04-13 19:21 UTC, GaryRidgway commented
I will pull down and test this

2022-04-13 19:44 UTC, GaryRidgway approved these changes
Everything looked great except for these icons on colored backgrounds:
![Screen Shot 2022-04-13 at 2 42 56 PM](https://user-images.githubusercontent.com/23122142/163257871-68f29ebb-7cb9-4700-9db9-63fb00029162.png)

2022-04-13 19:46 UTC, GaryRidgway approved these changes
Actually, I think it wouldn't be too hard to change those to have a transparent background instead of a white one, can we make that change first and then I'll come back and approve again?

2022-04-13 19:47 UTC, GaryRidgway requested changes
I meant to request changes for the above approval.

2022-04-13 20:15 UTC, bewoldt commented
I added a fix for the glyph horizontal rule.

2022-04-13 20:15 UTC, bspeare commented
I'm also testing a few things out here on a few sites.

2022-04-13 20:20 UTC, bspeare commented on docroot/themes/custom/uids_base/scss/webforms/webforms.scss
> +    & .form-item {
@bewoldt can you take a look at these flexbox layouts on https://sandbox.uiowa.ddev.site/webform-layouts and try removing these lines and look at the spacing issue?

2022-04-13 20:23 UTC, bspeare commented
Should we try to fix this issue in this?  https://github.com/uiowa/uiowa/issues/3486#issuecomment-1090720811.

2022-04-13 20:32 UTC, bspeare commented
The style updates look great!  Maybe add `.5rem` margin under these `<legend>` items to get a little more space?

<img width="462" alt="Screen Shot 2022-04-13 at 3 31 03 PM" src="https://user-images.githubusercontent.com/1036433/163265345-35d56969-d356-4201-b6b0-c3c2511bc11a.png">

2022-04-13 20:35 UTC, bspeare commented
Also, @bewoldt do you remember how to recreate this issue that you were having with the field turning gold?  https://github.com/uiowa/uiowa/issues/5002

2022-04-13 20:38 UTC, bewoldt commented
> 

Add a text field and for the Title use "Submitter's Name" or anything with the word submit.

2022-04-13 20:51 UTC, bspeare commented
I updated the selector that was making the field gold to resolve https://github.com/uiowa/uiowa/issues/5002.

2022-04-14 14:49 UTC, GaryRidgway approved these changes

2022-04-14 14:49 UTC, GaryRidgway commented
Just re-reviewed, looks good to me!

2022-04-14 15:43 UTC, merged