Classrooms - Room list view
uiowa/uiowa pull request #6122
Opened 2023-01-23 23:37 UTC by joewhitsitt

initial work on rooms list and gotchas

2023-01-25 18:37 UTC, bspeare commented
It looks like we need this patch or upgrade the module to get the min/max fieldset to appear within the "Filters" details: https://www.drupal.org/project/better_exposed_filters/issues/3175500#comment-14297189.   @joewhitsitt what do you think?

2023-01-25 18:44 UTC, joewhitsitt commented
i'd vote upgrade unless unless our patch from https://www.drupal.org/project/better_exposed_filters/issues/3103626 no longer applies...

2023-01-25 19:30 UTC, joewhitsitt commented
Upgrading worked @bspeare. Nice find!

<img width="333" alt="Screen Shot 2023-01-25 at 1 29 11 PM" src="https://user-images.githubusercontent.com/4663676/214668098-93905c8b-1471-451b-8f08-1b6e060fd551.png">

2023-01-26 22:30 UTC, cory-skeers commented
Focus keeps getting placed on maximum/max occupancy while interacting with the form. Example below:

https://user-images.githubusercontent.com/49074566/214964407-eb22d2b8-62ba-4ebb-912d-78bb935ce6a1.mov

The scrolling is jarring, and like in the example above while using the text field, if there's a pause in typing the filtering starts, and the focus shift moves the cursor as well.

2023-01-26 23:00 UTC, cory-skeers commented
It looks like we have a patch related to the focus already (https://www.drupal.org/project/better_exposed_filters/issues/3103626), but that it's not working entirely as expected with multiple text and select boxes.

One adjustment I tried locally was moving the combined text field to the last filter applied (visually still first), and in that case any form submission shifts focus to it. It's still not 100% desirable, but in the cases of using a select box or typing in that field already, it helps.

2023-01-27 14:45 UTC, joewhitsitt commented
Bummer. I forgot to test that after seeing it apply successfully. I can poke around a bit

2023-01-27 16:04 UTC, joewhitsitt commented
Updating the patch did not work 😞

2023-01-27 16:21 UTC, cory-skeers commented
Couple other notes:

- Furniture type filter isn't on there. I kinda remember that might have been consolidated as part of "room features," but not sure.
- Should the capacity (max occupancy) be inside the "Filters" group? Currently if you collapse filters you get the free text search as well as occupancy
- The "Room Details" button in the teasers don't seem to be linked

I primarily got through testing that all the filters worked as expected, excluded things they were supposed to, etc., and had just gotten into testing functionality of the links and such. Going to unassign myself, but can re-test things when you get the occupancy stuff working @joewhitsitt.

2023-01-27 16:36 UTC, joewhitsitt commented
>Furniture type filter isn't on there. I kinda remember that might have been consolidated as part of "room features," but not sure.

Good eye, though I don't think we want to add this as a filter even though it was part of the IS. This is a multi-text field so it would probably be added to the combined text filter instead of as a separate filter. @briand44 do you think we can get away with not adding that one?

>Should the capacity (max occupancy) be inside the "Filters" group? Currently if you collapse filters you get the free text search as well as occupancy

It _was_ at one point. I am re-creating that filter though so I will make sure it is back in there.

>The "Room Details" button in the teasers don't seem to be linked

I think that is our faux-button technology. It is a feature that it doesn't appear linked but the whole card is a giant link.

2023-01-27 16:59 UTC, joewhitsitt commented
Just to note. Composer install was needed to update BEF initially to allow the max occupancy field (range) to be added to the details fieldset. I had to change the filter anyway though to work with the focus stuff.

<img width="351" alt="Screen Shot 2023-01-27 at 10 56 55 AM" src="https://user-images.githubusercontent.com/4663676/215147274-f1199798-b8d8-494a-882c-869ef8c15da8.png">
<img width="355" alt="Screen Shot 2023-01-27 at 10 57 02 AM" src="https://user-images.githubusercontent.com/4663676/215147276-7a0fd266-5243-4cb1-b98c-f5819f230d89.png">

2023-01-27 17:10 UTC, joewhitsitt commented
>Furniture type filter isn't on there. I kinda remember that might have been consolidated as part of "room features," but not sure.

>>Good eye, though I don't think we want to add this as a filter even though it was part of the IS. This is a multi-text field so it would probably be added to the combined text filter instead of as a separate filter. @briand44 do you think we can get away with not adding that one?

I think we should hold off on this for now.

2023-01-27 17:23 UTC, cory-skeers commented
> > The "Room Details" button in the teasers don't seem to be linked
> 
> I think that is our faux-button technology. It is a feature that it doesn't appear linked but the whole card is a giant link.

I went back and re-checked this, and it looks like the faux-button is working as expected on initial load, but after the teasers are reloaded from an AJAX call, only the card headline is linked and the rest of the cards are no longer linked.

I'm wondering if it might be a bad interaction with the focus stuff? If so, it might be fixed by the recent work (I haven't pulled the newer commits yet).

2023-01-27 17:27 UTC, joewhitsitt commented
>I went back and re-checked this, and it looks like the faux-button is working as expected on initial load, but after the teasers are reloaded from an AJAX call, only the card headline is linked and the rest of the cards are no longer linked.

Ooh interesting. Bummer to the max

2023-01-27 17:54 UTC, briand44 commented
There does not need to be a filter for Furniture. https://github.com/uiowa/uiowa/issues/6041#issue-1503576829

Apologies for having it incorrectly in the IS.

2023-01-27 17:57 UTC, cory-skeers requested changes

2023-01-27 17:57 UTC, cory-skeers commented on config/sites/classrooms.uiowa.edu/views.view.room_list.yml
> +                title: '25 or less'
Tiny nit if you don't mind 😬 

```suggestion
                title: '25 or fewer'
```

2023-01-27 18:04 UTC, joewhitsitt commented
document.querySelectorAll from docroot/themes/custom/uids_base/uids3/assets/js/click-a11y.js grabs a static list from my five minutes of research on Google. For it to grab a new list after AJAX call, we have to do some stuff different?

This appears to be an issue with ajax pagers too out on prod. after the first page, the linking is lost.

2023-01-27 18:31 UTC, pyrello commented
> document.querySelectorAll from docroot/themes/custom/uids_base/uids3/assets/js/click-a11y.js grabs a static list from my five minutes of research on Google. For it to grab a new list after AJAX call, we have to do some stuff different?
> 
> This appears to be an issue with ajax pagers too out on prod. after the first page, the linking is lost.
> 
> https://stackoverflow.com/questions/54157042/cant-access-new-elements-after-ajax-call-vanilla-js

We may not be appropriately wrapping the click ally script so that it is trigger upon a document fragment being added to the DOM. I think we are maybe just including it as is.

Good find, @joewhitsitt! We have ourselves a bug!

2023-01-27 21:46 UTC, bspeare commented
Do we want to change "Apply" to "Search"?  I think we are using "Search" on most of our exposed forms.

2023-01-27 22:32 UTC, bspeare commented
Should we switch back to horizontal search now that the occupancy field has changed?

<img width="1390" alt="Screen Shot 2023-01-27 at 4 31 25 PM" src="https://user-images.githubusercontent.com/1036433/215218691-6b23fd8a-2454-43cb-939b-56b26b611d0f.png">

2023-01-27 22:46 UTC, joewhitsitt commented
ipad air (1180px) still kind of seems smooshed. i am fine with leaving it as-is, but if we only made the change because of max occupancy being a range input then we can switch it back. I felt like we sold the sidebar when we pointed out the pattern was being used on other big sites.

2023-01-27 22:55 UTC, bspeare commented
The sidebar seems more smushed too.  Maybe we switch to a 33-67 layout if we don't go to the horizontal?

<img width="945" alt="Screen Shot 2023-01-27 at 4 53 20 PM" src="https://user-images.githubusercontent.com/1036433/215221377-5228a1a9-29d0-4821-8f56-e7309ba7e7e4.png">

2023-01-30 14:56 UTC, bspeare commented
Also, if we stick with the sidebar maybe move to a card list?  The stacked get a bit tall. 

<details>
<img width="1416" alt="Screen Shot 2023-01-30 at 8 37 33 AM" src="https://user-images.githubusercontent.com/1036433/215511886-9cf97bd2-3c54-4bd8-a411-117b96bf69d3.png">
</details>

2023-01-30 15:12 UTC, joewhitsitt commented
Alright, twist my arm. Seems like horizontal will be the lesser at this point and match the originally approved mockup. I'll try to make that change here shortly.

2023-01-30 15:15 UTC, pyrello commented
I can resolve these conflicts.

2023-01-30 15:18 UTC, pyrello commented
> I can resolve these conflicts.

Or @joewhitsitt can do it, I guess.

2023-01-30 15:19 UTC, joewhitsitt commented
Sorry. didn't see the notification

2023-01-30 15:28 UTC, joewhitsitt commented
I _think_ it is ready to review again. Update the PR instructions. Ignoring https://github.com/uiowa/uiowa/issues/6138 for now.

2023-01-30 15:50 UTC, cory-skeers commented
Pulling down to test again

2023-01-30 16:24 UTC, cory-skeers commented on docroot/themes/custom/uids_base/scss/views/view-bef.scss
> +
Is this left over from the previous sidebar view, or is this part of the overlap with other work?

2023-01-30 16:26 UTC, bspeare commented on docroot/themes/custom/uids_base/scss/views/view-bef.scss
> +
This is a modifier style that can be used in the future if we want to use this bef form in a sidebar.

2023-01-30 16:27 UTC, cory-skeers commented on docroot/themes/custom/uids_base/scss/views/view-bef.scss
> +
Cool--and judging from previous testing it worked out well, so I'd say it's good to approve without further testing at this point.

2023-01-30 16:27 UTC, bspeare commented on docroot/themes/custom/uids_base/scss/views/view-bef.scss
> +
If we switch back to the range fields as mentioned in https://github.com/uiowa/uiowa/pull/6122#issuecomment-1407161632, we will need this.

2023-01-30 16:28 UTC, cory-skeers approved these changes
Re-tested going through updated instructions, and everything looks good to go! 👍

2023-01-30 17:02 UTC, e-marie-w commented
Also working as expected for me so I unassigned myself.

2023-01-30 17:09 UTC, merged