Futureproof sitenow events code
uiowa/uiowa pull request #825
Opened 2019-12-10 21:22 UTC by joewhitsitt

2019-12-10 21:43 UTC, richardbporter requested changes

2019-12-10 21:43 UTC, richardbporter commented on docroot/modules/custom/sitenow_events/src/Controller/EventsController.php
> +   * @var \Drupal\Core\Config\ImmutableConfig
This should match the parameter type in the constructor docblock.

2019-12-10 21:56 UTC, richardbporter commented
Do you see the configure form locally? Could be my environment but I'm not.

2019-12-10 21:59 UTC, richardbporter approved these changes

2019-12-11 15:39 UTC, richardbporter commented
I fixed the menu link issue. Are webmasters supposed to have permission to manage sitenow events?

2019-12-11 15:58 UTC, joewhitsitt commented
yes

2019-12-11 16:13 UTC, richardbporter approved these changes

2019-12-11 16:21 UTC, merged